@startuml

actor "foo1" as client
participant "app-server" as app
boundary "boundary" as border
participant "access"

autonumber
client --> app: req token
app --> border: req token
border --> app: rsp(token)
app --> client: rsp(token)
client --> border: req access(token)
border --> client: rsp(access node)
client --> access: link init(token)
access --> client: link done

@enduml
