@startuml

actor "foo1" as client1

participant "access" as access1
participant "group-server" as group
database "storage" as db
participant "access" as access2
actor "foo2" as client2

autonumber
client1 --> access1 : msg publish
access1 --> group: msg up stream
group --> group: validation
group --> db: save msg
group --> access1: msg up ACK
access1 --> client1 : publish ack(msg_id, sent_time)

group --> access2: msg down stream
access2 --> client2: msg notify
client2 --> access2: notify ack
@enduml
