// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.tim.common.protos;

public final class History {
  private History() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HisMessagesReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tim.common.protos.HisMessagesReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    java.lang.String getConversasionId();
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    com.google.protobuf.ByteString
        getConversasionIdBytes();
  }
  /**
   * <pre>
   * 历史消息请求
   * </pre>
   *
   * Protobuf type {@code com.tim.common.protos.HisMessagesReq}
   */
  public  static final class HisMessagesReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tim.common.protos.HisMessagesReq)
      HisMessagesReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HisMessagesReq.newBuilder() to construct.
    private HisMessagesReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HisMessagesReq() {
      id_ = "";
      conversasionId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HisMessagesReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              conversasionId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tim.common.protos.History.HisMessagesReq.class, com.tim.common.protos.History.HisMessagesReq.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONVERSASIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object conversasionId_;
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    public java.lang.String getConversasionId() {
      java.lang.Object ref = conversasionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversasionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConversasionIdBytes() {
      java.lang.Object ref = conversasionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversasionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getConversasionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conversasionId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getConversasionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conversasionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tim.common.protos.History.HisMessagesReq)) {
        return super.equals(obj);
      }
      com.tim.common.protos.History.HisMessagesReq other = (com.tim.common.protos.History.HisMessagesReq) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getConversasionId()
          .equals(other.getConversasionId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CONVERSASIONID_FIELD_NUMBER;
      hash = (53 * hash) + getConversasionId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.History.HisMessagesReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tim.common.protos.History.HisMessagesReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 历史消息请求
     * </pre>
     *
     * Protobuf type {@code com.tim.common.protos.HisMessagesReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tim.common.protos.HisMessagesReq)
        com.tim.common.protos.History.HisMessagesReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tim.common.protos.History.HisMessagesReq.class, com.tim.common.protos.History.HisMessagesReq.Builder.class);
      }

      // Construct using com.tim.common.protos.History.HisMessagesReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        conversasionId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesReq_descriptor;
      }

      @java.lang.Override
      public com.tim.common.protos.History.HisMessagesReq getDefaultInstanceForType() {
        return com.tim.common.protos.History.HisMessagesReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.tim.common.protos.History.HisMessagesReq build() {
        com.tim.common.protos.History.HisMessagesReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tim.common.protos.History.HisMessagesReq buildPartial() {
        com.tim.common.protos.History.HisMessagesReq result = new com.tim.common.protos.History.HisMessagesReq(this);
        result.id_ = id_;
        result.conversasionId_ = conversasionId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tim.common.protos.History.HisMessagesReq) {
          return mergeFrom((com.tim.common.protos.History.HisMessagesReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tim.common.protos.History.HisMessagesReq other) {
        if (other == com.tim.common.protos.History.HisMessagesReq.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getConversasionId().isEmpty()) {
          conversasionId_ = other.conversasionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tim.common.protos.History.HisMessagesReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tim.common.protos.History.HisMessagesReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object conversasionId_ = "";
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public java.lang.String getConversasionId() {
        java.lang.Object ref = conversasionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conversasionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getConversasionIdBytes() {
        java.lang.Object ref = conversasionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conversasionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public Builder setConversasionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conversasionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public Builder clearConversasionId() {
        
        conversasionId_ = getDefaultInstance().getConversasionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public Builder setConversasionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        conversasionId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tim.common.protos.HisMessagesReq)
    }

    // @@protoc_insertion_point(class_scope:com.tim.common.protos.HisMessagesReq)
    private static final com.tim.common.protos.History.HisMessagesReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tim.common.protos.History.HisMessagesReq();
    }

    public static com.tim.common.protos.History.HisMessagesReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HisMessagesReq>
        PARSER = new com.google.protobuf.AbstractParser<HisMessagesReq>() {
      @java.lang.Override
      public HisMessagesReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HisMessagesReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HisMessagesReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HisMessagesReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tim.common.protos.History.HisMessagesReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HisMessagesAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tim.common.protos.HisMessagesAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    java.lang.String getConversasionId();
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    com.google.protobuf.ByteString
        getConversasionIdBytes();

    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    java.util.List<com.tim.common.protos.Common.MessageContent> 
        getMessageListList();
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    com.tim.common.protos.Common.MessageContent getMessageList(int index);
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    int getMessageListCount();
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    java.util.List<? extends com.tim.common.protos.Common.MessageContentOrBuilder> 
        getMessageListOrBuilderList();
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    com.tim.common.protos.Common.MessageContentOrBuilder getMessageListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 历史消息
   * </pre>
   *
   * Protobuf type {@code com.tim.common.protos.HisMessagesAck}
   */
  public  static final class HisMessagesAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tim.common.protos.HisMessagesAck)
      HisMessagesAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HisMessagesAck.newBuilder() to construct.
    private HisMessagesAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HisMessagesAck() {
      id_ = "";
      conversasionId_ = "";
      messageList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HisMessagesAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              conversasionId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                messageList_ = new java.util.ArrayList<com.tim.common.protos.Common.MessageContent>();
                mutable_bitField0_ |= 0x00000004;
              }
              messageList_.add(
                  input.readMessage(com.tim.common.protos.Common.MessageContent.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          messageList_ = java.util.Collections.unmodifiableList(messageList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tim.common.protos.History.HisMessagesAck.class, com.tim.common.protos.History.HisMessagesAck.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONVERSASIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object conversasionId_;
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    public java.lang.String getConversasionId() {
      java.lang.Object ref = conversasionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversasionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversasionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConversasionIdBytes() {
      java.lang.Object ref = conversasionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversasionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGELIST_FIELD_NUMBER = 3;
    private java.util.List<com.tim.common.protos.Common.MessageContent> messageList_;
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    public java.util.List<com.tim.common.protos.Common.MessageContent> getMessageListList() {
      return messageList_;
    }
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    public java.util.List<? extends com.tim.common.protos.Common.MessageContentOrBuilder> 
        getMessageListOrBuilderList() {
      return messageList_;
    }
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    public int getMessageListCount() {
      return messageList_.size();
    }
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    public com.tim.common.protos.Common.MessageContent getMessageList(int index) {
      return messageList_.get(index);
    }
    /**
     * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
     */
    public com.tim.common.protos.Common.MessageContentOrBuilder getMessageListOrBuilder(
        int index) {
      return messageList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getConversasionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conversasionId_);
      }
      for (int i = 0; i < messageList_.size(); i++) {
        output.writeMessage(3, messageList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getConversasionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conversasionId_);
      }
      for (int i = 0; i < messageList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, messageList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tim.common.protos.History.HisMessagesAck)) {
        return super.equals(obj);
      }
      com.tim.common.protos.History.HisMessagesAck other = (com.tim.common.protos.History.HisMessagesAck) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getConversasionId()
          .equals(other.getConversasionId());
      result = result && getMessageListList()
          .equals(other.getMessageListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CONVERSASIONID_FIELD_NUMBER;
      hash = (53 * hash) + getConversasionId().hashCode();
      if (getMessageListCount() > 0) {
        hash = (37 * hash) + MESSAGELIST_FIELD_NUMBER;
        hash = (53 * hash) + getMessageListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.History.HisMessagesAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tim.common.protos.History.HisMessagesAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 历史消息
     * </pre>
     *
     * Protobuf type {@code com.tim.common.protos.HisMessagesAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tim.common.protos.HisMessagesAck)
        com.tim.common.protos.History.HisMessagesAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tim.common.protos.History.HisMessagesAck.class, com.tim.common.protos.History.HisMessagesAck.Builder.class);
      }

      // Construct using com.tim.common.protos.History.HisMessagesAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        conversasionId_ = "";

        if (messageListBuilder_ == null) {
          messageList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          messageListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tim.common.protos.History.internal_static_com_tim_common_protos_HisMessagesAck_descriptor;
      }

      @java.lang.Override
      public com.tim.common.protos.History.HisMessagesAck getDefaultInstanceForType() {
        return com.tim.common.protos.History.HisMessagesAck.getDefaultInstance();
      }

      @java.lang.Override
      public com.tim.common.protos.History.HisMessagesAck build() {
        com.tim.common.protos.History.HisMessagesAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tim.common.protos.History.HisMessagesAck buildPartial() {
        com.tim.common.protos.History.HisMessagesAck result = new com.tim.common.protos.History.HisMessagesAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.conversasionId_ = conversasionId_;
        if (messageListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            messageList_ = java.util.Collections.unmodifiableList(messageList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.messageList_ = messageList_;
        } else {
          result.messageList_ = messageListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tim.common.protos.History.HisMessagesAck) {
          return mergeFrom((com.tim.common.protos.History.HisMessagesAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tim.common.protos.History.HisMessagesAck other) {
        if (other == com.tim.common.protos.History.HisMessagesAck.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getConversasionId().isEmpty()) {
          conversasionId_ = other.conversasionId_;
          onChanged();
        }
        if (messageListBuilder_ == null) {
          if (!other.messageList_.isEmpty()) {
            if (messageList_.isEmpty()) {
              messageList_ = other.messageList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMessageListIsMutable();
              messageList_.addAll(other.messageList_);
            }
            onChanged();
          }
        } else {
          if (!other.messageList_.isEmpty()) {
            if (messageListBuilder_.isEmpty()) {
              messageListBuilder_.dispose();
              messageListBuilder_ = null;
              messageList_ = other.messageList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              messageListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageListFieldBuilder() : null;
            } else {
              messageListBuilder_.addAllMessages(other.messageList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tim.common.protos.History.HisMessagesAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tim.common.protos.History.HisMessagesAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object conversasionId_ = "";
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public java.lang.String getConversasionId() {
        java.lang.Object ref = conversasionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conversasionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getConversasionIdBytes() {
        java.lang.Object ref = conversasionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conversasionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public Builder setConversasionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conversasionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public Builder clearConversasionId() {
        
        conversasionId_ = getDefaultInstance().getConversasionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 会话id
       * </pre>
       *
       * <code>string conversasionId = 2;</code>
       */
      public Builder setConversasionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        conversasionId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.tim.common.protos.Common.MessageContent> messageList_ =
        java.util.Collections.emptyList();
      private void ensureMessageListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          messageList_ = new java.util.ArrayList<com.tim.common.protos.Common.MessageContent>(messageList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tim.common.protos.Common.MessageContent, com.tim.common.protos.Common.MessageContent.Builder, com.tim.common.protos.Common.MessageContentOrBuilder> messageListBuilder_;

      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public java.util.List<com.tim.common.protos.Common.MessageContent> getMessageListList() {
        if (messageListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messageList_);
        } else {
          return messageListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public int getMessageListCount() {
        if (messageListBuilder_ == null) {
          return messageList_.size();
        } else {
          return messageListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public com.tim.common.protos.Common.MessageContent getMessageList(int index) {
        if (messageListBuilder_ == null) {
          return messageList_.get(index);
        } else {
          return messageListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder setMessageList(
          int index, com.tim.common.protos.Common.MessageContent value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.set(index, value);
          onChanged();
        } else {
          messageListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder setMessageList(
          int index, com.tim.common.protos.Common.MessageContent.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder addMessageList(com.tim.common.protos.Common.MessageContent value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.add(value);
          onChanged();
        } else {
          messageListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder addMessageList(
          int index, com.tim.common.protos.Common.MessageContent value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.add(index, value);
          onChanged();
        } else {
          messageListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder addMessageList(
          com.tim.common.protos.Common.MessageContent.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.add(builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder addMessageList(
          int index, com.tim.common.protos.Common.MessageContent.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder addAllMessageList(
          java.lang.Iterable<? extends com.tim.common.protos.Common.MessageContent> values) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messageList_);
          onChanged();
        } else {
          messageListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder clearMessageList() {
        if (messageListBuilder_ == null) {
          messageList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          messageListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public Builder removeMessageList(int index) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.remove(index);
          onChanged();
        } else {
          messageListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public com.tim.common.protos.Common.MessageContent.Builder getMessageListBuilder(
          int index) {
        return getMessageListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public com.tim.common.protos.Common.MessageContentOrBuilder getMessageListOrBuilder(
          int index) {
        if (messageListBuilder_ == null) {
          return messageList_.get(index);  } else {
          return messageListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public java.util.List<? extends com.tim.common.protos.Common.MessageContentOrBuilder> 
           getMessageListOrBuilderList() {
        if (messageListBuilder_ != null) {
          return messageListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messageList_);
        }
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public com.tim.common.protos.Common.MessageContent.Builder addMessageListBuilder() {
        return getMessageListFieldBuilder().addBuilder(
            com.tim.common.protos.Common.MessageContent.getDefaultInstance());
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public com.tim.common.protos.Common.MessageContent.Builder addMessageListBuilder(
          int index) {
        return getMessageListFieldBuilder().addBuilder(
            index, com.tim.common.protos.Common.MessageContent.getDefaultInstance());
      }
      /**
       * <code>repeated .com.tim.common.protos.MessageContent messageList = 3;</code>
       */
      public java.util.List<com.tim.common.protos.Common.MessageContent.Builder> 
           getMessageListBuilderList() {
        return getMessageListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tim.common.protos.Common.MessageContent, com.tim.common.protos.Common.MessageContent.Builder, com.tim.common.protos.Common.MessageContentOrBuilder> 
          getMessageListFieldBuilder() {
        if (messageListBuilder_ == null) {
          messageListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tim.common.protos.Common.MessageContent, com.tim.common.protos.Common.MessageContent.Builder, com.tim.common.protos.Common.MessageContentOrBuilder>(
                  messageList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          messageList_ = null;
        }
        return messageListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tim.common.protos.HisMessagesAck)
    }

    // @@protoc_insertion_point(class_scope:com.tim.common.protos.HisMessagesAck)
    private static final com.tim.common.protos.History.HisMessagesAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tim.common.protos.History.HisMessagesAck();
    }

    public static com.tim.common.protos.History.HisMessagesAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HisMessagesAck>
        PARSER = new com.google.protobuf.AbstractParser<HisMessagesAck>() {
      @java.lang.Override
      public HisMessagesAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HisMessagesAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HisMessagesAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HisMessagesAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tim.common.protos.History.HisMessagesAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tim_common_protos_HisMessagesReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tim_common_protos_HisMessagesReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tim_common_protos_HisMessagesAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tim_common_protos_HisMessagesAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rhistory.proto\022\025com.tim.common.protos\032\014" +
      "common.proto\"4\n\016HisMessagesReq\022\n\n\002id\030\001 \001" +
      "(\t\022\026\n\016conversasionId\030\002 \001(\t\"p\n\016HisMessage" +
      "sAck\022\n\n\002id\030\001 \001(\t\022\026\n\016conversasionId\030\002 \001(\t" +
      "\022:\n\013messageList\030\003 \003(\0132%.com.tim.common.p" +
      "rotos.MessageContentB\tB\007Historyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tim.common.protos.Common.getDescriptor(),
        }, assigner);
    internal_static_com_tim_common_protos_HisMessagesReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tim_common_protos_HisMessagesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tim_common_protos_HisMessagesReq_descriptor,
        new java.lang.String[] { "Id", "ConversasionId", });
    internal_static_com_tim_common_protos_HisMessagesAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tim_common_protos_HisMessagesAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tim_common_protos_HisMessagesAck_descriptor,
        new java.lang.String[] { "Id", "ConversasionId", "MessageList", });
    com.tim.common.protos.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
