// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.tim.common.protos;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * Protobuf enum {@code com.tim.common.protos.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *单人会话
     * </pre>
     *
     * <code>PERSON = 0;</code>
     */
    PERSON(0),
    /**
     * <pre>
     *群消息
     * </pre>
     *
     * <code>GROUP = 1;</code>
     */
    GROUP(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *单人会话
     * </pre>
     *
     * <code>PERSON = 0;</code>
     */
    public static final int PERSON_VALUE = 0;
    /**
     * <pre>
     *群消息
     * </pre>
     *
     * <code>GROUP = 1;</code>
     */
    public static final int GROUP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return PERSON;
        case 1: return GROUP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tim.common.protos.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.tim.common.protos.MsgType)
  }

  public interface UpStreamMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tim.common.protos.UpStreamMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    java.util.List<java.lang.String>
        getTouidList();
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    int getTouidCount();
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    java.lang.String getTouid(int index);
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    com.google.protobuf.ByteString
        getTouidBytes(int index);

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 2;</code>
     */
    int getProtonum();

    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>uint64 sendtime = 4;</code>
     */
    long getSendtime();

    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 5;</code>
     */
    java.lang.String getMsgid();
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgidBytes();
  }
  /**
   * <pre>
   *上行单聊消息
   * </pre>
   *
   * Protobuf type {@code com.tim.common.protos.UpStreamMessage}
   */
  public  static final class UpStreamMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tim.common.protos.UpStreamMessage)
      UpStreamMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpStreamMessage.newBuilder() to construct.
    private UpStreamMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpStreamMessage() {
      touid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      protonum_ = 0;
      content_ = "";
      sendtime_ = 0L;
      msgid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpStreamMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                touid_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              touid_.add(s);
              break;
            }
            case 16: {

              protonum_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              sendtime_ = input.readUInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              msgid_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          touid_ = touid_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tim.common.protos.Message.internal_static_com_tim_common_protos_UpStreamMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tim.common.protos.Message.internal_static_com_tim_common_protos_UpStreamMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tim.common.protos.Message.UpStreamMessage.class, com.tim.common.protos.Message.UpStreamMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TOUID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList touid_;
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTouidList() {
      return touid_;
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    public int getTouidCount() {
      return touid_.size();
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    public java.lang.String getTouid(int index) {
      return touid_.get(index);
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>repeated string touid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTouidBytes(int index) {
      return touid_.getByteString(index);
    }

    public static final int PROTONUM_FIELD_NUMBER = 2;
    private int protonum_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 2;</code>
     */
    public int getProtonum() {
      return protonum_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 4;
    private long sendtime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>uint64 sendtime = 4;</code>
     */
    public long getSendtime() {
      return sendtime_;
    }

    public static final int MSGID_FIELD_NUMBER = 5;
    private volatile java.lang.Object msgid_;
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 5;</code>
     */
    public java.lang.String getMsgid() {
      java.lang.Object ref = msgid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgidBytes() {
      java.lang.Object ref = msgid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < touid_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, touid_.getRaw(i));
      }
      if (protonum_ != 0) {
        output.writeUInt32(2, protonum_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (sendtime_ != 0L) {
        output.writeUInt64(4, sendtime_);
      }
      if (!getMsgidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < touid_.size(); i++) {
          dataSize += computeStringSizeNoTag(touid_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTouidList().size();
      }
      if (protonum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, protonum_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (sendtime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sendtime_);
      }
      if (!getMsgidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tim.common.protos.Message.UpStreamMessage)) {
        return super.equals(obj);
      }
      com.tim.common.protos.Message.UpStreamMessage other = (com.tim.common.protos.Message.UpStreamMessage) obj;

      boolean result = true;
      result = result && getTouidList()
          .equals(other.getTouidList());
      result = result && (getProtonum()
          == other.getProtonum());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getSendtime()
          == other.getSendtime());
      result = result && getMsgid()
          .equals(other.getMsgid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTouidCount() > 0) {
        hash = (37 * hash) + TOUID_FIELD_NUMBER;
        hash = (53 * hash) + getTouidList().hashCode();
      }
      hash = (37 * hash) + PROTONUM_FIELD_NUMBER;
      hash = (53 * hash) + getProtonum();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendtime());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.Message.UpStreamMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tim.common.protos.Message.UpStreamMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *上行单聊消息
     * </pre>
     *
     * Protobuf type {@code com.tim.common.protos.UpStreamMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tim.common.protos.UpStreamMessage)
        com.tim.common.protos.Message.UpStreamMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tim.common.protos.Message.internal_static_com_tim_common_protos_UpStreamMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tim.common.protos.Message.internal_static_com_tim_common_protos_UpStreamMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tim.common.protos.Message.UpStreamMessage.class, com.tim.common.protos.Message.UpStreamMessage.Builder.class);
      }

      // Construct using com.tim.common.protos.Message.UpStreamMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        touid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        protonum_ = 0;

        content_ = "";

        sendtime_ = 0L;

        msgid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tim.common.protos.Message.internal_static_com_tim_common_protos_UpStreamMessage_descriptor;
      }

      @java.lang.Override
      public com.tim.common.protos.Message.UpStreamMessage getDefaultInstanceForType() {
        return com.tim.common.protos.Message.UpStreamMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.tim.common.protos.Message.UpStreamMessage build() {
        com.tim.common.protos.Message.UpStreamMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tim.common.protos.Message.UpStreamMessage buildPartial() {
        com.tim.common.protos.Message.UpStreamMessage result = new com.tim.common.protos.Message.UpStreamMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          touid_ = touid_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.touid_ = touid_;
        result.protonum_ = protonum_;
        result.content_ = content_;
        result.sendtime_ = sendtime_;
        result.msgid_ = msgid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tim.common.protos.Message.UpStreamMessage) {
          return mergeFrom((com.tim.common.protos.Message.UpStreamMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tim.common.protos.Message.UpStreamMessage other) {
        if (other == com.tim.common.protos.Message.UpStreamMessage.getDefaultInstance()) return this;
        if (!other.touid_.isEmpty()) {
          if (touid_.isEmpty()) {
            touid_ = other.touid_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTouidIsMutable();
            touid_.addAll(other.touid_);
          }
          onChanged();
        }
        if (other.getProtonum() != 0) {
          setProtonum(other.getProtonum());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getSendtime() != 0L) {
          setSendtime(other.getSendtime());
        }
        if (!other.getMsgid().isEmpty()) {
          msgid_ = other.msgid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tim.common.protos.Message.UpStreamMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tim.common.protos.Message.UpStreamMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList touid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTouidIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          touid_ = new com.google.protobuf.LazyStringArrayList(touid_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTouidList() {
        return touid_.getUnmodifiableView();
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public int getTouidCount() {
        return touid_.size();
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public java.lang.String getTouid(int index) {
        return touid_.get(index);
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTouidBytes(int index) {
        return touid_.getByteString(index);
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public Builder setTouid(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTouidIsMutable();
        touid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public Builder addTouid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTouidIsMutable();
        touid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public Builder addAllTouid(
          java.lang.Iterable<java.lang.String> values) {
        ensureTouidIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, touid_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public Builder clearTouid() {
        touid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>repeated string touid = 1;</code>
       */
      public Builder addTouidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTouidIsMutable();
        touid_.add(value);
        onChanged();
        return this;
      }

      private int protonum_ ;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 2;</code>
       */
      public int getProtonum() {
        return protonum_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 2;</code>
       */
      public Builder setProtonum(int value) {
        
        protonum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 2;</code>
       */
      public Builder clearProtonum() {
        
        protonum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long sendtime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>uint64 sendtime = 4;</code>
       */
      public long getSendtime() {
        return sendtime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>uint64 sendtime = 4;</code>
       */
      public Builder setSendtime(long value) {
        
        sendtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>uint64 sendtime = 4;</code>
       */
      public Builder clearSendtime() {
        
        sendtime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msgid_ = "";
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 5;</code>
       */
      public java.lang.String getMsgid() {
        java.lang.Object ref = msgid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgidBytes() {
        java.lang.Object ref = msgid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 5;</code>
       */
      public Builder setMsgid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 5;</code>
       */
      public Builder clearMsgid() {
        
        msgid_ = getDefaultInstance().getMsgid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 5;</code>
       */
      public Builder setMsgidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tim.common.protos.UpStreamMessage)
    }

    // @@protoc_insertion_point(class_scope:com.tim.common.protos.UpStreamMessage)
    private static final com.tim.common.protos.Message.UpStreamMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tim.common.protos.Message.UpStreamMessage();
    }

    public static com.tim.common.protos.Message.UpStreamMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpStreamMessage>
        PARSER = new com.google.protobuf.AbstractParser<UpStreamMessage>() {
      @java.lang.Override
      public UpStreamMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpStreamMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpStreamMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpStreamMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tim.common.protos.Message.UpStreamMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DownStreamMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tim.common.protos.DownStreamMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    java.lang.String getFromuid();
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromuidBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.tim.common.protos.MsgType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.tim.common.protos.MsgType type = 2;</code>
     */
    com.tim.common.protos.Message.MsgType getType();

    /**
     * <pre>
     *如果是群消息那么指定群Id
     * </pre>
     *
     * <code>string groupuid = 3;</code>
     */
    java.lang.String getGroupuid();
    /**
     * <pre>
     *如果是群消息那么指定群Id
     * </pre>
     *
     * <code>string groupuid = 3;</code>
     */
    com.google.protobuf.ByteString
        getGroupuidBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 4;</code>
     */
    int getProtonum();

    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 sendtime = 6;</code>
     */
    long getSendtime();

    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 7;</code>
     */
    java.lang.String getMsgid();
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 7;</code>
     */
    com.google.protobuf.ByteString
        getMsgidBytes();
  }
  /**
   * <pre>
   *下行消息
   * </pre>
   *
   * Protobuf type {@code com.tim.common.protos.DownStreamMessage}
   */
  public  static final class DownStreamMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tim.common.protos.DownStreamMessage)
      DownStreamMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DownStreamMessage.newBuilder() to construct.
    private DownStreamMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DownStreamMessage() {
      fromuid_ = "";
      type_ = 0;
      groupuid_ = "";
      protonum_ = 0;
      content_ = "";
      sendtime_ = 0L;
      msgid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DownStreamMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fromuid_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              groupuid_ = s;
              break;
            }
            case 32: {

              protonum_ = input.readUInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 48: {

              sendtime_ = input.readUInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              msgid_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tim.common.protos.Message.internal_static_com_tim_common_protos_DownStreamMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tim.common.protos.Message.internal_static_com_tim_common_protos_DownStreamMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tim.common.protos.Message.DownStreamMessage.class, com.tim.common.protos.Message.DownStreamMessage.Builder.class);
    }

    public static final int FROMUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object fromuid_;
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    public java.lang.String getFromuid() {
      java.lang.Object ref = fromuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromuidBytes() {
      java.lang.Object ref = fromuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.tim.common.protos.MsgType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.tim.common.protos.MsgType type = 2;</code>
     */
    public com.tim.common.protos.Message.MsgType getType() {
      @SuppressWarnings("deprecation")
      com.tim.common.protos.Message.MsgType result = com.tim.common.protos.Message.MsgType.valueOf(type_);
      return result == null ? com.tim.common.protos.Message.MsgType.UNRECOGNIZED : result;
    }

    public static final int GROUPUID_FIELD_NUMBER = 3;
    private volatile java.lang.Object groupuid_;
    /**
     * <pre>
     *如果是群消息那么指定群Id
     * </pre>
     *
     * <code>string groupuid = 3;</code>
     */
    public java.lang.String getGroupuid() {
      java.lang.Object ref = groupuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *如果是群消息那么指定群Id
     * </pre>
     *
     * <code>string groupuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGroupuidBytes() {
      java.lang.Object ref = groupuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTONUM_FIELD_NUMBER = 4;
    private int protonum_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 4;</code>
     */
    public int getProtonum() {
      return protonum_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>string content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 6;
    private long sendtime_;
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 sendtime = 6;</code>
     */
    public long getSendtime() {
      return sendtime_;
    }

    public static final int MSGID_FIELD_NUMBER = 7;
    private volatile java.lang.Object msgid_;
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 7;</code>
     */
    public java.lang.String getMsgid() {
      java.lang.Object ref = msgid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>string msgid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMsgidBytes() {
      java.lang.Object ref = msgid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFromuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromuid_);
      }
      if (type_ != com.tim.common.protos.Message.MsgType.PERSON.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getGroupuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, groupuid_);
      }
      if (protonum_ != 0) {
        output.writeUInt32(4, protonum_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (sendtime_ != 0L) {
        output.writeUInt64(6, sendtime_);
      }
      if (!getMsgidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromuid_);
      }
      if (type_ != com.tim.common.protos.Message.MsgType.PERSON.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getGroupuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, groupuid_);
      }
      if (protonum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, protonum_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (sendtime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, sendtime_);
      }
      if (!getMsgidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tim.common.protos.Message.DownStreamMessage)) {
        return super.equals(obj);
      }
      com.tim.common.protos.Message.DownStreamMessage other = (com.tim.common.protos.Message.DownStreamMessage) obj;

      boolean result = true;
      result = result && getFromuid()
          .equals(other.getFromuid());
      result = result && type_ == other.type_;
      result = result && getGroupuid()
          .equals(other.getGroupuid());
      result = result && (getProtonum()
          == other.getProtonum());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getSendtime()
          == other.getSendtime());
      result = result && getMsgid()
          .equals(other.getMsgid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROMUID_FIELD_NUMBER;
      hash = (53 * hash) + getFromuid().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + GROUPUID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupuid().hashCode();
      hash = (37 * hash) + PROTONUM_FIELD_NUMBER;
      hash = (53 * hash) + getProtonum();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendtime());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tim.common.protos.Message.DownStreamMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tim.common.protos.Message.DownStreamMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *下行消息
     * </pre>
     *
     * Protobuf type {@code com.tim.common.protos.DownStreamMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tim.common.protos.DownStreamMessage)
        com.tim.common.protos.Message.DownStreamMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tim.common.protos.Message.internal_static_com_tim_common_protos_DownStreamMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tim.common.protos.Message.internal_static_com_tim_common_protos_DownStreamMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tim.common.protos.Message.DownStreamMessage.class, com.tim.common.protos.Message.DownStreamMessage.Builder.class);
      }

      // Construct using com.tim.common.protos.Message.DownStreamMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromuid_ = "";

        type_ = 0;

        groupuid_ = "";

        protonum_ = 0;

        content_ = "";

        sendtime_ = 0L;

        msgid_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tim.common.protos.Message.internal_static_com_tim_common_protos_DownStreamMessage_descriptor;
      }

      @java.lang.Override
      public com.tim.common.protos.Message.DownStreamMessage getDefaultInstanceForType() {
        return com.tim.common.protos.Message.DownStreamMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.tim.common.protos.Message.DownStreamMessage build() {
        com.tim.common.protos.Message.DownStreamMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tim.common.protos.Message.DownStreamMessage buildPartial() {
        com.tim.common.protos.Message.DownStreamMessage result = new com.tim.common.protos.Message.DownStreamMessage(this);
        result.fromuid_ = fromuid_;
        result.type_ = type_;
        result.groupuid_ = groupuid_;
        result.protonum_ = protonum_;
        result.content_ = content_;
        result.sendtime_ = sendtime_;
        result.msgid_ = msgid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tim.common.protos.Message.DownStreamMessage) {
          return mergeFrom((com.tim.common.protos.Message.DownStreamMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tim.common.protos.Message.DownStreamMessage other) {
        if (other == com.tim.common.protos.Message.DownStreamMessage.getDefaultInstance()) return this;
        if (!other.getFromuid().isEmpty()) {
          fromuid_ = other.fromuid_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getGroupuid().isEmpty()) {
          groupuid_ = other.groupuid_;
          onChanged();
        }
        if (other.getProtonum() != 0) {
          setProtonum(other.getProtonum());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getSendtime() != 0L) {
          setSendtime(other.getSendtime());
        }
        if (!other.getMsgid().isEmpty()) {
          msgid_ = other.msgid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tim.common.protos.Message.DownStreamMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tim.common.protos.Message.DownStreamMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fromuid_ = "";
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public java.lang.String getFromuid() {
        java.lang.Object ref = fromuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromuidBytes() {
        java.lang.Object ref = fromuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public Builder setFromuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public Builder clearFromuid() {
        
        fromuid_ = getDefaultInstance().getFromuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public Builder setFromuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromuid_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.tim.common.protos.MsgType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.tim.common.protos.MsgType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.tim.common.protos.MsgType type = 2;</code>
       */
      public com.tim.common.protos.Message.MsgType getType() {
        @SuppressWarnings("deprecation")
        com.tim.common.protos.Message.MsgType result = com.tim.common.protos.Message.MsgType.valueOf(type_);
        return result == null ? com.tim.common.protos.Message.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.tim.common.protos.MsgType type = 2;</code>
       */
      public Builder setType(com.tim.common.protos.Message.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.tim.common.protos.MsgType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object groupuid_ = "";
      /**
       * <pre>
       *如果是群消息那么指定群Id
       * </pre>
       *
       * <code>string groupuid = 3;</code>
       */
      public java.lang.String getGroupuid() {
        java.lang.Object ref = groupuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *如果是群消息那么指定群Id
       * </pre>
       *
       * <code>string groupuid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGroupuidBytes() {
        java.lang.Object ref = groupuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *如果是群消息那么指定群Id
       * </pre>
       *
       * <code>string groupuid = 3;</code>
       */
      public Builder setGroupuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *如果是群消息那么指定群Id
       * </pre>
       *
       * <code>string groupuid = 3;</code>
       */
      public Builder clearGroupuid() {
        
        groupuid_ = getDefaultInstance().getGroupuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *如果是群消息那么指定群Id
       * </pre>
       *
       * <code>string groupuid = 3;</code>
       */
      public Builder setGroupuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupuid_ = value;
        onChanged();
        return this;
      }

      private int protonum_ ;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 4;</code>
       */
      public int getProtonum() {
        return protonum_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 4;</code>
       */
      public Builder setProtonum(int value) {
        
        protonum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 4;</code>
       */
      public Builder clearProtonum() {
        
        protonum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>string content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long sendtime_ ;
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 sendtime = 6;</code>
       */
      public long getSendtime() {
        return sendtime_;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 sendtime = 6;</code>
       */
      public Builder setSendtime(long value) {
        
        sendtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 sendtime = 6;</code>
       */
      public Builder clearSendtime() {
        
        sendtime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msgid_ = "";
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 7;</code>
       */
      public java.lang.String getMsgid() {
        java.lang.Object ref = msgid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMsgidBytes() {
        java.lang.Object ref = msgid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 7;</code>
       */
      public Builder setMsgid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 7;</code>
       */
      public Builder clearMsgid() {
        
        msgid_ = getDefaultInstance().getMsgid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>string msgid = 7;</code>
       */
      public Builder setMsgidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgid_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tim.common.protos.DownStreamMessage)
    }

    // @@protoc_insertion_point(class_scope:com.tim.common.protos.DownStreamMessage)
    private static final com.tim.common.protos.Message.DownStreamMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tim.common.protos.Message.DownStreamMessage();
    }

    public static com.tim.common.protos.Message.DownStreamMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DownStreamMessage>
        PARSER = new com.google.protobuf.AbstractParser<DownStreamMessage>() {
      @java.lang.Override
      public DownStreamMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DownStreamMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DownStreamMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DownStreamMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tim.common.protos.Message.DownStreamMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tim_common_protos_UpStreamMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tim_common_protos_UpStreamMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tim_common_protos_DownStreamMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tim_common_protos_DownStreamMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\025com.tim.common.protos\"d" +
      "\n\017UpStreamMessage\022\r\n\005touid\030\001 \003(\t\022\020\n\010prot" +
      "onum\030\002 \001(\r\022\017\n\007content\030\003 \001(\t\022\020\n\010sendtime\030" +
      "\004 \001(\004\022\r\n\005msgid\030\005 \001(\t\"\250\001\n\021DownStreamMessa" +
      "ge\022\017\n\007fromuid\030\001 \001(\t\022,\n\004type\030\002 \001(\0162\036.com." +
      "tim.common.protos.MsgType\022\020\n\010groupuid\030\003 " +
      "\001(\t\022\020\n\010protonum\030\004 \001(\r\022\017\n\007content\030\005 \001(\t\022\020" +
      "\n\010sendtime\030\006 \001(\004\022\r\n\005msgid\030\007 \001(\t* \n\007MsgTy" +
      "pe\022\n\n\006PERSON\020\000\022\t\n\005GROUP\020\001B\tB\007Messageb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tim_common_protos_UpStreamMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tim_common_protos_UpStreamMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tim_common_protos_UpStreamMessage_descriptor,
        new java.lang.String[] { "Touid", "Protonum", "Content", "Sendtime", "Msgid", });
    internal_static_com_tim_common_protos_DownStreamMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tim_common_protos_DownStreamMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tim_common_protos_DownStreamMessage_descriptor,
        new java.lang.String[] { "Fromuid", "Type", "Groupuid", "Protonum", "Content", "Sendtime", "Msgid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
