// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package cn.timmy.common.protos;

public final class HeartBeat {
  private HeartBeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.timmy.proto.protos.Beat)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string heartbeat = 1;</code>
     */
    String getHeartbeat();
    /**
     * <code>string heartbeat = 1;</code>
     */
    com.google.protobuf.ByteString
        getHeartbeatBytes();
  }
  /**
   * Protobuf type {@code cn.timmy.proto.protos.Beat}
   */
  public  static final class Beat extends
      com.google.protobuf.GeneratedMessageLite<
          Beat, Beat.Builder> implements
      // @@protoc_insertion_point(message_implements:cn.timmy.proto.protos.Beat)
      BeatOrBuilder {
    private Beat() {
      heartbeat_ = "";
    }
    public static final int HEARTBEAT_FIELD_NUMBER = 1;
    private String heartbeat_;
    /**
     * <code>string heartbeat = 1;</code>
     */
    public String getHeartbeat() {
      return heartbeat_;
    }
    /**
     * <code>string heartbeat = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHeartbeatBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(heartbeat_);
    }
    /**
     * <code>string heartbeat = 1;</code>
     */
    private void setHeartbeat(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      heartbeat_ = value;
    }
    /**
     * <code>string heartbeat = 1;</code>
     */
    private void clearHeartbeat() {

      heartbeat_ = getDefaultInstance().getHeartbeat();
    }
    /**
     * <code>string heartbeat = 1;</code>
     */
    private void setHeartbeatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      heartbeat_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!heartbeat_.isEmpty()) {
        output.writeString(1, getHeartbeat());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!heartbeat_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getHeartbeat());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static HeartBeat.Beat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static HeartBeat.Beat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static HeartBeat.Beat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static HeartBeat.Beat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static HeartBeat.Beat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static HeartBeat.Beat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static HeartBeat.Beat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static HeartBeat.Beat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static HeartBeat.Beat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static HeartBeat.Beat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static HeartBeat.Beat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static HeartBeat.Beat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(HeartBeat.Beat prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code cn.timmy.proto.protos.Beat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          HeartBeat.Beat, Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.timmy.proto.protos.Beat)
        HeartBeat.BeatOrBuilder {
      // Construct using cn.timmy.proto.protos.HeartBeat.Beat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string heartbeat = 1;</code>
       */
      public String getHeartbeat() {
        return instance.getHeartbeat();
      }
      /**
       * <code>string heartbeat = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHeartbeatBytes() {
        return instance.getHeartbeatBytes();
      }
      /**
       * <code>string heartbeat = 1;</code>
       */
      public Builder setHeartbeat(
          String value) {
        copyOnWrite();
        instance.setHeartbeat(value);
        return this;
      }
      /**
       * <code>string heartbeat = 1;</code>
       */
      public Builder clearHeartbeat() {
        copyOnWrite();
        instance.clearHeartbeat();
        return this;
      }
      /**
       * <code>string heartbeat = 1;</code>
       */
      public Builder setHeartbeatBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHeartbeatBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cn.timmy.proto.protos.Beat)
    }
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new HeartBeat.Beat();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          HeartBeat.Beat other = (HeartBeat.Beat) arg1;
          heartbeat_ = visitor.visitString(!heartbeat_.isEmpty(), heartbeat_,
              !other.heartbeat_.isEmpty(), other.heartbeat_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  heartbeat_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (HeartBeat.Beat.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:cn.timmy.proto.protos.Beat)
    private static final HeartBeat.Beat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Beat();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static HeartBeat.Beat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Beat> PARSER;

    public static com.google.protobuf.Parser<Beat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
