// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify.proto

package cn.timmy.common.protos;

public final class Notify {
  private Notify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NotifyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.timmy.common.protos.NotifyMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    java.lang.String getFromuid();
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromuidBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 2;</code>
     */
    int getProtonum();

    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 sendtime = 5;</code>
     */
    long getSendtime();

    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>uint64 msgid = 6;</code>
     */
    long getMsgid();
  }
  /**
   * <pre>
   *通知消息
   * </pre>
   *
   * Protobuf type {@code cn.timmy.common.protos.NotifyMessage}
   */
  public  static final class NotifyMessage extends
      com.google.protobuf.GeneratedMessageLite<
          NotifyMessage, NotifyMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:cn.timmy.common.protos.NotifyMessage)
      NotifyMessageOrBuilder {
    private NotifyMessage() {
      fromuid_ = "";
      type_ = "";
      content_ = "";
    }
    public static final int FROMUID_FIELD_NUMBER = 1;
    private java.lang.String fromuid_;
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    public java.lang.String getFromuid() {
      return fromuid_;
    }
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromuidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fromuid_);
    }
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    private void setFromuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromuid_ = value;
    }
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    private void clearFromuid() {
      
      fromuid_ = getDefaultInstance().getFromuid();
    }
    /**
     * <pre>
     * 发送方uid
     * </pre>
     *
     * <code>string fromuid = 1;</code>
     */
    private void setFromuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromuid_ = value.toStringUtf8();
    }

    public static final int PROTONUM_FIELD_NUMBER = 2;
    private int protonum_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 2;</code>
     */
    public int getProtonum() {
      return protonum_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 2;</code>
     */
    private void setProtonum(int value) {
      
      protonum_ = value;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 protonum = 2;</code>
     */
    private void clearProtonum() {
      
      protonum_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.String type_;
    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    public java.lang.String getType() {
      return type_;
    }
    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    private void setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
    }
    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <pre>
     * 通知类型
     * </pre>
     *
     * <code>string type = 3;</code>
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value.toStringUtf8();
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private java.lang.String content_;
    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
    }
    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    private void clearContent() {
      
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <pre>
     * 通知内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value.toStringUtf8();
    }

    public static final int SENDTIME_FIELD_NUMBER = 5;
    private long sendtime_;
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 sendtime = 5;</code>
     */
    public long getSendtime() {
      return sendtime_;
    }
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 sendtime = 5;</code>
     */
    private void setSendtime(long value) {
      
      sendtime_ = value;
    }
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 sendtime = 5;</code>
     */
    private void clearSendtime() {
      
      sendtime_ = 0L;
    }

    public static final int MSGID_FIELD_NUMBER = 6;
    private long msgid_;
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>uint64 msgid = 6;</code>
     */
    public long getMsgid() {
      return msgid_;
    }
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>uint64 msgid = 6;</code>
     */
    private void setMsgid(long value) {
      
      msgid_ = value;
    }
    /**
     * <pre>
     *消息唯一标示
     * </pre>
     *
     * <code>uint64 msgid = 6;</code>
     */
    private void clearMsgid() {
      
      msgid_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!fromuid_.isEmpty()) {
        output.writeString(1, getFromuid());
      }
      if (protonum_ != 0) {
        output.writeUInt32(2, protonum_);
      }
      if (!type_.isEmpty()) {
        output.writeString(3, getType());
      }
      if (!content_.isEmpty()) {
        output.writeString(4, getContent());
      }
      if (sendtime_ != 0L) {
        output.writeUInt64(5, sendtime_);
      }
      if (msgid_ != 0L) {
        output.writeUInt64(6, msgid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!fromuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFromuid());
      }
      if (protonum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, protonum_);
      }
      if (!type_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getType());
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getContent());
      }
      if (sendtime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sendtime_);
      }
      if (msgid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, msgid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static cn.timmy.common.protos.Notify.NotifyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(cn.timmy.common.protos.Notify.NotifyMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *通知消息
     * </pre>
     *
     * Protobuf type {@code cn.timmy.common.protos.NotifyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          cn.timmy.common.protos.Notify.NotifyMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.timmy.common.protos.NotifyMessage)
        cn.timmy.common.protos.Notify.NotifyMessageOrBuilder {
      // Construct using cn.timmy.common.protos.Notify.NotifyMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public java.lang.String getFromuid() {
        return instance.getFromuid();
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromuidBytes() {
        return instance.getFromuidBytes();
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public Builder setFromuid(
          java.lang.String value) {
        copyOnWrite();
        instance.setFromuid(value);
        return this;
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public Builder clearFromuid() {
        copyOnWrite();
        instance.clearFromuid();
        return this;
      }
      /**
       * <pre>
       * 发送方uid
       * </pre>
       *
       * <code>string fromuid = 1;</code>
       */
      public Builder setFromuidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFromuidBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 2;</code>
       */
      public int getProtonum() {
        return instance.getProtonum();
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 2;</code>
       */
      public Builder setProtonum(int value) {
        copyOnWrite();
        instance.setProtonum(value);
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 protonum = 2;</code>
       */
      public Builder clearProtonum() {
        copyOnWrite();
        instance.clearProtonum();
        return this;
      }

      /**
       * <pre>
       * 通知类型
       * </pre>
       *
       * <code>string type = 3;</code>
       */
      public java.lang.String getType() {
        return instance.getType();
      }
      /**
       * <pre>
       * 通知类型
       * </pre>
       *
       * <code>string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <pre>
       * 通知类型
       * </pre>
       *
       * <code>string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       * 通知类型
       * </pre>
       *
       * <code>string type = 3;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <pre>
       * 通知类型
       * </pre>
       *
       * <code>string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      /**
       * <pre>
       * 通知内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <pre>
       * 通知内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <pre>
       * 通知内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <pre>
       * 通知内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <pre>
       * 通知内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 sendtime = 5;</code>
       */
      public long getSendtime() {
        return instance.getSendtime();
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 sendtime = 5;</code>
       */
      public Builder setSendtime(long value) {
        copyOnWrite();
        instance.setSendtime(value);
        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 sendtime = 5;</code>
       */
      public Builder clearSendtime() {
        copyOnWrite();
        instance.clearSendtime();
        return this;
      }

      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>uint64 msgid = 6;</code>
       */
      public long getMsgid() {
        return instance.getMsgid();
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>uint64 msgid = 6;</code>
       */
      public Builder setMsgid(long value) {
        copyOnWrite();
        instance.setMsgid(value);
        return this;
      }
      /**
       * <pre>
       *消息唯一标示
       * </pre>
       *
       * <code>uint64 msgid = 6;</code>
       */
      public Builder clearMsgid() {
        copyOnWrite();
        instance.clearMsgid();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cn.timmy.common.protos.NotifyMessage)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cn.timmy.common.protos.Notify.NotifyMessage();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          cn.timmy.common.protos.Notify.NotifyMessage other = (cn.timmy.common.protos.Notify.NotifyMessage) arg1;
          fromuid_ = visitor.visitString(!fromuid_.isEmpty(), fromuid_,
              !other.fromuid_.isEmpty(), other.fromuid_);
          protonum_ = visitor.visitInt(protonum_ != 0, protonum_,
              other.protonum_ != 0, other.protonum_);
          type_ = visitor.visitString(!type_.isEmpty(), type_,
              !other.type_.isEmpty(), other.type_);
          content_ = visitor.visitString(!content_.isEmpty(), content_,
              !other.content_.isEmpty(), other.content_);
          sendtime_ = visitor.visitLong(sendtime_ != 0L, sendtime_,
              other.sendtime_ != 0L, other.sendtime_);
          msgid_ = visitor.visitLong(msgid_ != 0L, msgid_,
              other.msgid_ != 0L, other.msgid_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  fromuid_ = s;
                  break;
                }
                case 16: {

                  protonum_ = input.readUInt32();
                  break;
                }
                case 26: {
                  java.lang.String s = input.readStringRequireUtf8();

                  type_ = s;
                  break;
                }
                case 34: {
                  java.lang.String s = input.readStringRequireUtf8();

                  content_ = s;
                  break;
                }
                case 40: {

                  sendtime_ = input.readUInt64();
                  break;
                }
                case 48: {

                  msgid_ = input.readUInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (cn.timmy.common.protos.Notify.NotifyMessage.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:cn.timmy.common.protos.NotifyMessage)
    private static final cn.timmy.common.protos.Notify.NotifyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NotifyMessage();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static cn.timmy.common.protos.Notify.NotifyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NotifyMessage> PARSER;

    public static com.google.protobuf.Parser<NotifyMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
