// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: private.message.proto

package protobuf.protos;

public final class PrivateMessageProto {

    private PrivateMessageProto() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * Protobuf enum {@code protobuf.protos.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.Internal.EnumLite {
        /**
         * <pre>
         * 单人会话
         * </pre>
         *
         * <code>PERSON = 0;</code>
         */
        PERSON(0),
        /**
         * <pre>
         * 群消息
         * </pre>
         *
         * <code>GROUP = 1;</code>
         */
        GROUP(1),
        UNRECOGNIZED(-1),;

        /**
         * <pre>
         * 单人会话
         * </pre>
         *
         * <code>PERSON = 0;</code>
         */
        public static final int PERSON_VALUE = 0;
        /**
         * <pre>
         * 群消息
         * </pre>
         *
         * <code>GROUP = 1;</code>
         */
        public static final int GROUP_VALUE = 1;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static MsgType valueOf(int value) {
            return forNumber(value);
        }

        public static MsgType forNumber(int value) {
            switch (value) {
                case 0:
                    return PERSON;
                case 1:
                    return GROUP;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
            MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
                public MsgType findValueByNumber(int number) {
                    return MsgType.forNumber(number);
                }
            };

        private final int value;

        private MsgType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:protobuf.protos.MsgType)
    }

    public interface UpStreamMessageProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.protos.UpStreamMessageProto)
        com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        java.util.List<java.lang.String>
        getTouidList();

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        int getTouidCount();

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        java.lang.String getTouid(int index);

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        com.google.protobuf.ByteString
        getTouidBytes(int index);

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 3;</code>
         */
        int getProtonum();

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        java.lang.String getContent();

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>uint64 sendtime = 5;</code>
         */
        long getSendtime();
    }

    /**
     * <pre>
     * 客户端发送单聊消息
     * </pre>
     *
     * Protobuf type {@code protobuf.protos.UpStreamMessageProto}
     */
    public static final class UpStreamMessageProto extends
        com.google.protobuf.GeneratedMessageLite<
            UpStreamMessageProto, UpStreamMessageProto.Builder> implements
        // @@protoc_insertion_point(message_implements:protobuf.protos.UpStreamMessageProto)
        UpStreamMessageProtoOrBuilder {

        private UpStreamMessageProto() {
            touid_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
            content_ = "";
        }

        private int bitField0_;
        public static final int TOUID_FIELD_NUMBER = 2;
        private com.google.protobuf.Internal.ProtobufList<java.lang.String> touid_;

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        public java.util.List<java.lang.String> getTouidList() {
            return touid_;
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        public int getTouidCount() {
            return touid_.size();
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        public java.lang.String getTouid(int index) {
            return touid_.get(index);
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTouidBytes(int index) {
            return com.google.protobuf.ByteString.copyFromUtf8(
                touid_.get(index));
        }

        private void ensureTouidIsMutable() {
            if (!touid_.isModifiable()) {
                touid_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(touid_);
            }
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        private void setTouid(
            int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureTouidIsMutable();
            touid_.set(index, value);
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        private void addTouid(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureTouidIsMutable();
            touid_.add(value);
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        private void addAllTouid(
            java.lang.Iterable<java.lang.String> values) {
            ensureTouidIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                values, touid_);
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        private void clearTouid() {
            touid_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        }

        /**
         * <pre>
         * 消息目标的userid
         * </pre>
         *
         * <code>repeated string touid = 2;</code>
         */
        private void addTouidBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureTouidIsMutable();
            touid_.add(value.toStringUtf8());
        }

        public static final int PROTONUM_FIELD_NUMBER = 3;
        private int protonum_;

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 3;</code>
         */
        public int getProtonum() {
            return protonum_;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 3;</code>
         */
        private void setProtonum(int value) {

            protonum_ = value;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 3;</code>
         */
        private void clearProtonum() {

            protonum_ = 0;
        }

        public static final int CONTENT_FIELD_NUMBER = 4;
        private java.lang.String content_;

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        public java.lang.String getContent() {
            return content_;
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(content_);
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        private void setContent(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            content_ = value;
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        private void clearContent() {

            content_ = getDefaultInstance().getContent();
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 4;</code>
         */
        private void setContentBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            content_ = value.toStringUtf8();
        }

        public static final int SENDTIME_FIELD_NUMBER = 5;
        private long sendtime_;

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>uint64 sendtime = 5;</code>
         */
        public long getSendtime() {
            return sendtime_;
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>uint64 sendtime = 5;</code>
         */
        private void setSendtime(long value) {

            sendtime_ = value;
        }

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>uint64 sendtime = 5;</code>
         */
        private void clearSendtime() {

            sendtime_ = 0L;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            for (int i = 0; i < touid_.size(); i++) {
                output.writeString(2, touid_.get(i));
            }
            if (protonum_ != 0) {
                output.writeUInt32(3, protonum_);
            }
            if (!content_.isEmpty()) {
                output.writeString(4, getContent());
            }
            if (sendtime_ != 0L) {
                output.writeUInt64(5, sendtime_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < touid_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                        .computeStringSizeNoTag(touid_.get(i));
                }
                size += dataSize;
                size += 1 * getTouidList().size();
            }
            if (protonum_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                    .computeUInt32Size(3, protonum_);
            }
            if (!content_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeStringSize(4, getContent());
            }
            if (sendtime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(5, sendtime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(
            protobuf.protos.PrivateMessageProto.UpStreamMessageProto prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * <pre>
         * 客户端发送单聊消息
         * </pre>
         *
         * Protobuf type {@code protobuf.protos.UpStreamMessageProto}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                protobuf.protos.PrivateMessageProto.UpStreamMessageProto, Builder> implements
            // @@protoc_insertion_point(builder_implements:protobuf.protos.UpStreamMessageProto)
            protobuf.protos.PrivateMessageProto.UpStreamMessageProtoOrBuilder {

            // Construct using protobuf.protos.PrivateMessageProto.UpStreamMessageProto.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public java.util.List<java.lang.String>
            getTouidList() {
                return java.util.Collections.unmodifiableList(
                    instance.getTouidList());
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public int getTouidCount() {
                return instance.getTouidCount();
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public java.lang.String getTouid(int index) {
                return instance.getTouid(index);
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTouidBytes(int index) {
                return instance.getTouidBytes(index);
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public Builder setTouid(
                int index, java.lang.String value) {
                copyOnWrite();
                instance.setTouid(index, value);
                return this;
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public Builder addTouid(
                java.lang.String value) {
                copyOnWrite();
                instance.addTouid(value);
                return this;
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public Builder addAllTouid(
                java.lang.Iterable<java.lang.String> values) {
                copyOnWrite();
                instance.addAllTouid(values);
                return this;
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public Builder clearTouid() {
                copyOnWrite();
                instance.clearTouid();
                return this;
            }

            /**
             * <pre>
             * 消息目标的userid
             * </pre>
             *
             * <code>repeated string touid = 2;</code>
             */
            public Builder addTouidBytes(
                com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.addTouidBytes(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>uint32 protonum = 3;</code>
             */
            public int getProtonum() {
                return instance.getProtonum();
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>uint32 protonum = 3;</code>
             */
            public Builder setProtonum(int value) {
                copyOnWrite();
                instance.setProtonum(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>uint32 protonum = 3;</code>
             */
            public Builder clearProtonum() {
                copyOnWrite();
                instance.clearProtonum();
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 4;</code>
             */
            public java.lang.String getContent() {
                return instance.getContent();
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 4;</code>
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                return instance.getContentBytes();
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 4;</code>
             */
            public Builder setContent(
                java.lang.String value) {
                copyOnWrite();
                instance.setContent(value);
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 4;</code>
             */
            public Builder clearContent() {
                copyOnWrite();
                instance.clearContent();
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 4;</code>
             */
            public Builder setContentBytes(
                com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setContentBytes(value);
                return this;
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>uint64 sendtime = 5;</code>
             */
            public long getSendtime() {
                return instance.getSendtime();
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>uint64 sendtime = 5;</code>
             */
            public Builder setSendtime(long value) {
                copyOnWrite();
                instance.setSendtime(value);
                return this;
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>uint64 sendtime = 5;</code>
             */
            public Builder clearSendtime() {
                copyOnWrite();
                instance.clearSendtime();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:protobuf.protos.UpStreamMessageProto)
        }

        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new protobuf.protos.PrivateMessageProto.UpStreamMessageProto();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    touid_.makeImmutable();
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    protobuf.protos.PrivateMessageProto.UpStreamMessageProto other = (protobuf.protos.PrivateMessageProto.UpStreamMessageProto) arg1;
                    touid_ = visitor.visitList(touid_, other.touid_);
                    protonum_ = visitor.visitInt(protonum_ != 0, protonum_,
                        other.protonum_ != 0, other.protonum_);
                    content_ = visitor.visitString(!content_.isEmpty(), content_,
                        !other.content_.isEmpty(), other.content_);
                    sendtime_ = visitor.visitLong(sendtime_ != 0L, sendtime_,
                        other.sendtime_ != 0L, other.sendtime_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                        .INSTANCE) {
                        bitField0_ |= other.bitField0_;
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                        (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                        (com.google.protobuf.ExtensionRegistryLite) arg1;
                    if (extensionRegistry == null) {
                        throw new java.lang.NullPointerException();
                    }
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 18: {
                                    java.lang.String s = input.readStringRequireUtf8();
                                    if (!touid_.isModifiable()) {
                                        touid_ =
                                            com.google.protobuf.GeneratedMessageLite
                                                .mutableCopy(touid_);
                                    }
                                    touid_.add(s);
                                    break;
                                }
                                case 24: {

                                    protonum_ = input.readUInt32();
                                    break;
                                }
                                case 34: {
                                    java.lang.String s = input.readStringRequireUtf8();

                                    content_ = s;
                                    break;
                                }
                                case 40: {

                                    sendtime_ = input.readUInt64();
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                            new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (protobuf.protos.PrivateMessageProto.UpStreamMessageProto.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:protobuf.protos.UpStreamMessageProto)
        private static final protobuf.protos.PrivateMessageProto.UpStreamMessageProto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new UpStreamMessageProto();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static protobuf.protos.PrivateMessageProto.UpStreamMessageProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<UpStreamMessageProto> PARSER;

        public static com.google.protobuf.Parser<UpStreamMessageProto> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface DownStreamMessageProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.protos.DownStreamMessageProto)
        com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        java.lang.String getFromuid();

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        com.google.protobuf.ByteString
        getFromuidBytes();

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        int getTypeValue();

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        protobuf.protos.PrivateMessageProto.MsgType getType();

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        java.lang.String getGroupuid();

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        com.google.protobuf.ByteString
        getGroupuidBytes();

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 4;</code>
         */
        int getProtonum();

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>bytes content = 5;</code>
         */
        com.google.protobuf.ByteString getContent();

        /**
         * <pre>
         * 消息时间
         * </pre>
         *
         * <code>uint64 sendtime = 6;</code>
         */
        long getSendtime();

        /**
         * <pre>
         * 消息唯一标示
         * </pre>
         *
         * <code>uint64 msgid = 7;</code>
         */
        long getMsgid();
    }

    /**
     * <pre>
     * 服务端发送消息
     * </pre>
     *
     * Protobuf type {@code protobuf.protos.DownStreamMessageProto}
     */
    public static final class DownStreamMessageProto extends
        com.google.protobuf.GeneratedMessageLite<
            DownStreamMessageProto, DownStreamMessageProto.Builder> implements
        // @@protoc_insertion_point(message_implements:protobuf.protos.DownStreamMessageProto)
        DownStreamMessageProtoOrBuilder {

        private DownStreamMessageProto() {
            fromuid_ = "";
            groupuid_ = "";
            content_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final int FROMUID_FIELD_NUMBER = 1;
        private java.lang.String fromuid_;

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        public java.lang.String getFromuid() {
            return fromuid_;
        }

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        public com.google.protobuf.ByteString
        getFromuidBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(fromuid_);
        }

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        private void setFromuid(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            fromuid_ = value;
        }

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        private void clearFromuid() {

            fromuid_ = getDefaultInstance().getFromuid();
        }

        /**
         * <pre>
         * 发送方uid
         * </pre>
         *
         * <code>string fromuid = 1;</code>
         */
        private void setFromuidBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            fromuid_ = value.toStringUtf8();
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        public int getTypeValue() {
            return type_;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        public protobuf.protos.PrivateMessageProto.MsgType getType() {
            protobuf.protos.PrivateMessageProto.MsgType result = protobuf.protos.PrivateMessageProto.MsgType
                .forNumber(type_);
            return result == null ? protobuf.protos.PrivateMessageProto.MsgType.UNRECOGNIZED
                : result;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        private void setTypeValue(int value) {
            type_ = value;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        private void setType(protobuf.protos.PrivateMessageProto.MsgType value) {
            if (value == null) {
                throw new NullPointerException();
            }

            type_ = value.getNumber();
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>.protobuf.protos.MsgType type = 2;</code>
         */
        private void clearType() {

            type_ = 0;
        }

        public static final int GROUPUID_FIELD_NUMBER = 3;
        private java.lang.String groupuid_;

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        public java.lang.String getGroupuid() {
            return groupuid_;
        }

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        public com.google.protobuf.ByteString
        getGroupuidBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(groupuid_);
        }

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        private void setGroupuid(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            groupuid_ = value;
        }

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        private void clearGroupuid() {

            groupuid_ = getDefaultInstance().getGroupuid();
        }

        /**
         * <pre>
         * 如果是群消息那么指定群groupId
         * </pre>
         *
         * <code>string groupuid = 3;</code>
         */
        private void setGroupuidBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            groupuid_ = value.toStringUtf8();
        }

        public static final int PROTONUM_FIELD_NUMBER = 4;
        private int protonum_;

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 4;</code>
         */
        public int getProtonum() {
            return protonum_;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 4;</code>
         */
        private void setProtonum(int value) {

            protonum_ = value;
        }

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>uint32 protonum = 4;</code>
         */
        private void clearProtonum() {

            protonum_ = 0;
        }

        public static final int CONTENT_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString content_;

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>bytes content = 5;</code>
         */
        public com.google.protobuf.ByteString getContent() {
            return content_;
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>bytes content = 5;</code>
         */
        private void setContent(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            content_ = value;
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>bytes content = 5;</code>
         */
        private void clearContent() {

            content_ = getDefaultInstance().getContent();
        }

        public static final int SENDTIME_FIELD_NUMBER = 6;
        private long sendtime_;

        /**
         * <pre>
         * 消息时间
         * </pre>
         *
         * <code>uint64 sendtime = 6;</code>
         */
        public long getSendtime() {
            return sendtime_;
        }

        /**
         * <pre>
         * 消息时间
         * </pre>
         *
         * <code>uint64 sendtime = 6;</code>
         */
        private void setSendtime(long value) {

            sendtime_ = value;
        }

        /**
         * <pre>
         * 消息时间
         * </pre>
         *
         * <code>uint64 sendtime = 6;</code>
         */
        private void clearSendtime() {

            sendtime_ = 0L;
        }

        public static final int MSGID_FIELD_NUMBER = 7;
        private long msgid_;

        /**
         * <pre>
         * 消息唯一标示
         * </pre>
         *
         * <code>uint64 msgid = 7;</code>
         */
        public long getMsgid() {
            return msgid_;
        }

        /**
         * <pre>
         * 消息唯一标示
         * </pre>
         *
         * <code>uint64 msgid = 7;</code>
         */
        private void setMsgid(long value) {

            msgid_ = value;
        }

        /**
         * <pre>
         * 消息唯一标示
         * </pre>
         *
         * <code>uint64 msgid = 7;</code>
         */
        private void clearMsgid() {

            msgid_ = 0L;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (!fromuid_.isEmpty()) {
                output.writeString(1, getFromuid());
            }
            if (type_ != protobuf.protos.PrivateMessageProto.MsgType.PERSON.getNumber()) {
                output.writeEnum(2, type_);
            }
            if (!groupuid_.isEmpty()) {
                output.writeString(3, getGroupuid());
            }
            if (protonum_ != 0) {
                output.writeUInt32(4, protonum_);
            }
            if (!content_.isEmpty()) {
                output.writeBytes(5, content_);
            }
            if (sendtime_ != 0L) {
                output.writeUInt64(6, sendtime_);
            }
            if (msgid_ != 0L) {
                output.writeUInt64(7, msgid_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!fromuid_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeStringSize(1, getFromuid());
            }
            if (type_ != protobuf.protos.PrivateMessageProto.MsgType.PERSON.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(2, type_);
            }
            if (!groupuid_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeStringSize(3, getGroupuid());
            }
            if (protonum_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                    .computeUInt32Size(4, protonum_);
            }
            if (!content_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(5, content_);
            }
            if (sendtime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(6, sendtime_);
            }
            if (msgid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(7, msgid_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(
            protobuf.protos.PrivateMessageProto.DownStreamMessageProto prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * <pre>
         * 服务端发送消息
         * </pre>
         *
         * Protobuf type {@code protobuf.protos.DownStreamMessageProto}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                protobuf.protos.PrivateMessageProto.DownStreamMessageProto, Builder> implements
            // @@protoc_insertion_point(builder_implements:protobuf.protos.DownStreamMessageProto)
            protobuf.protos.PrivateMessageProto.DownStreamMessageProtoOrBuilder {

            // Construct using protobuf.protos.PrivateMessageProto.DownStreamMessageProto.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <pre>
             * 发送方uid
             * </pre>
             *
             * <code>string fromuid = 1;</code>
             */
            public java.lang.String getFromuid() {
                return instance.getFromuid();
            }

            /**
             * <pre>
             * 发送方uid
             * </pre>
             *
             * <code>string fromuid = 1;</code>
             */
            public com.google.protobuf.ByteString
            getFromuidBytes() {
                return instance.getFromuidBytes();
            }

            /**
             * <pre>
             * 发送方uid
             * </pre>
             *
             * <code>string fromuid = 1;</code>
             */
            public Builder setFromuid(
                java.lang.String value) {
                copyOnWrite();
                instance.setFromuid(value);
                return this;
            }

            /**
             * <pre>
             * 发送方uid
             * </pre>
             *
             * <code>string fromuid = 1;</code>
             */
            public Builder clearFromuid() {
                copyOnWrite();
                instance.clearFromuid();
                return this;
            }

            /**
             * <pre>
             * 发送方uid
             * </pre>
             *
             * <code>string fromuid = 1;</code>
             */
            public Builder setFromuidBytes(
                com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setFromuidBytes(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>.protobuf.protos.MsgType type = 2;</code>
             */
            public int getTypeValue() {
                return instance.getTypeValue();
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>.protobuf.protos.MsgType type = 2;</code>
             */
            public Builder setTypeValue(int value) {
                copyOnWrite();
                instance.setTypeValue(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>.protobuf.protos.MsgType type = 2;</code>
             */
            public protobuf.protos.PrivateMessageProto.MsgType getType() {
                return instance.getType();
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>.protobuf.protos.MsgType type = 2;</code>
             */
            public Builder setType(protobuf.protos.PrivateMessageProto.MsgType value) {
                copyOnWrite();
                instance.setType(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>.protobuf.protos.MsgType type = 2;</code>
             */
            public Builder clearType() {
                copyOnWrite();
                instance.clearType();
                return this;
            }

            /**
             * <pre>
             * 如果是群消息那么指定群groupId
             * </pre>
             *
             * <code>string groupuid = 3;</code>
             */
            public java.lang.String getGroupuid() {
                return instance.getGroupuid();
            }

            /**
             * <pre>
             * 如果是群消息那么指定群groupId
             * </pre>
             *
             * <code>string groupuid = 3;</code>
             */
            public com.google.protobuf.ByteString
            getGroupuidBytes() {
                return instance.getGroupuidBytes();
            }

            /**
             * <pre>
             * 如果是群消息那么指定群groupId
             * </pre>
             *
             * <code>string groupuid = 3;</code>
             */
            public Builder setGroupuid(
                java.lang.String value) {
                copyOnWrite();
                instance.setGroupuid(value);
                return this;
            }

            /**
             * <pre>
             * 如果是群消息那么指定群groupId
             * </pre>
             *
             * <code>string groupuid = 3;</code>
             */
            public Builder clearGroupuid() {
                copyOnWrite();
                instance.clearGroupuid();
                return this;
            }

            /**
             * <pre>
             * 如果是群消息那么指定群groupId
             * </pre>
             *
             * <code>string groupuid = 3;</code>
             */
            public Builder setGroupuidBytes(
                com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setGroupuidBytes(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>uint32 protonum = 4;</code>
             */
            public int getProtonum() {
                return instance.getProtonum();
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>uint32 protonum = 4;</code>
             */
            public Builder setProtonum(int value) {
                copyOnWrite();
                instance.setProtonum(value);
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>uint32 protonum = 4;</code>
             */
            public Builder clearProtonum() {
                copyOnWrite();
                instance.clearProtonum();
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>bytes content = 5;</code>
             */
            public com.google.protobuf.ByteString getContent() {
                return instance.getContent();
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>bytes content = 5;</code>
             */
            public Builder setContent(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setContent(value);
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>bytes content = 5;</code>
             */
            public Builder clearContent() {
                copyOnWrite();
                instance.clearContent();
                return this;
            }

            /**
             * <pre>
             * 消息时间
             * </pre>
             *
             * <code>uint64 sendtime = 6;</code>
             */
            public long getSendtime() {
                return instance.getSendtime();
            }

            /**
             * <pre>
             * 消息时间
             * </pre>
             *
             * <code>uint64 sendtime = 6;</code>
             */
            public Builder setSendtime(long value) {
                copyOnWrite();
                instance.setSendtime(value);
                return this;
            }

            /**
             * <pre>
             * 消息时间
             * </pre>
             *
             * <code>uint64 sendtime = 6;</code>
             */
            public Builder clearSendtime() {
                copyOnWrite();
                instance.clearSendtime();
                return this;
            }

            /**
             * <pre>
             * 消息唯一标示
             * </pre>
             *
             * <code>uint64 msgid = 7;</code>
             */
            public long getMsgid() {
                return instance.getMsgid();
            }

            /**
             * <pre>
             * 消息唯一标示
             * </pre>
             *
             * <code>uint64 msgid = 7;</code>
             */
            public Builder setMsgid(long value) {
                copyOnWrite();
                instance.setMsgid(value);
                return this;
            }

            /**
             * <pre>
             * 消息唯一标示
             * </pre>
             *
             * <code>uint64 msgid = 7;</code>
             */
            public Builder clearMsgid() {
                copyOnWrite();
                instance.clearMsgid();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:protobuf.protos.DownStreamMessageProto)
        }

        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new protobuf.protos.PrivateMessageProto.DownStreamMessageProto();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    protobuf.protos.PrivateMessageProto.DownStreamMessageProto other = (protobuf.protos.PrivateMessageProto.DownStreamMessageProto) arg1;
                    fromuid_ = visitor.visitString(!fromuid_.isEmpty(), fromuid_,
                        !other.fromuid_.isEmpty(), other.fromuid_);
                    type_ = visitor.visitInt(type_ != 0, type_, other.type_ != 0, other.type_);
                    groupuid_ = visitor.visitString(!groupuid_.isEmpty(), groupuid_,
                        !other.groupuid_.isEmpty(), other.groupuid_);
                    protonum_ = visitor.visitInt(protonum_ != 0, protonum_,
                        other.protonum_ != 0, other.protonum_);
                    content_ = visitor
                        .visitByteString(content_ != com.google.protobuf.ByteString.EMPTY, content_,
                            other.content_ != com.google.protobuf.ByteString.EMPTY, other.content_);
                    sendtime_ = visitor.visitLong(sendtime_ != 0L, sendtime_,
                        other.sendtime_ != 0L, other.sendtime_);
                    msgid_ = visitor.visitLong(msgid_ != 0L, msgid_,
                        other.msgid_ != 0L, other.msgid_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                        .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                        (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                        (com.google.protobuf.ExtensionRegistryLite) arg1;
                    if (extensionRegistry == null) {
                        throw new java.lang.NullPointerException();
                    }
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    java.lang.String s = input.readStringRequireUtf8();

                                    fromuid_ = s;
                                    break;
                                }
                                case 16: {
                                    int rawValue = input.readEnum();

                                    type_ = rawValue;
                                    break;
                                }
                                case 26: {
                                    java.lang.String s = input.readStringRequireUtf8();

                                    groupuid_ = s;
                                    break;
                                }
                                case 32: {

                                    protonum_ = input.readUInt32();
                                    break;
                                }
                                case 42: {

                                    content_ = input.readBytes();
                                    break;
                                }
                                case 48: {

                                    sendtime_ = input.readUInt64();
                                    break;
                                }
                                case 56: {

                                    msgid_ = input.readUInt64();
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                            new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (protobuf.protos.PrivateMessageProto.DownStreamMessageProto.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:protobuf.protos.DownStreamMessageProto)
        private static final protobuf.protos.PrivateMessageProto.DownStreamMessageProto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new DownStreamMessageProto();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static protobuf.protos.PrivateMessageProto.DownStreamMessageProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<DownStreamMessageProto> PARSER;

        public static com.google.protobuf.Parser<DownStreamMessageProto> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
